# Use Ctrl-a instead of Ctrl-b as the prefix
# From https://wiki.archlinux.org/index.php/Tmux
unbind C-b
set -g prefix C-a
bind C-a send-prefix


### I don't know what this is for, please find out?
set-option -g default-shell $SHELL
###


### For using pbcopy in tmux
# Source: https://github.com/tmux/tmux/issues/543#issuecomment-248980734
set-option -g default-command "reattach-to-user-namespace -l ${SHELL}"
###


### When creating new pane / splitting pane, use the same directory as the pane from where the command is run
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
###
